force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>This Object is used to hold Invoice and Credit Memo details to be synced from NS</description>
    <label>Invoice/Credit Memo</label>
    <nameField>
        <displayFormat>INV/CM-{0000}</displayFormat>
        <label>Invoice/CM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Invoice</description>
    <inlineHelpText>Lookup to Invoice</inlineHelpText>
    <label>Invoice ID</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Opportunity</description>
    <inlineHelpText>Lookup to Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SOCancelController.cls
public class SOCancelController {
    @AuraEnabled
    public static String soCancelMethod(Id recordId)
    {
        String status;
        String saleOrderCode;
        System.debug(recordId);
        List<Invoice__c> lstInv = [Select Id,Opportunity__c From Invoice__c where Opportunity__c =:recordId];
        Opportunity opp = [Select Id,Uniware_Internal_SO_No__c from Opportunity where Id=:recordId];
        saleOrderCode = opp.Uniware_Internal_SO_No__c;
        
        if(lstInv.size() > 0){
            status = 'Error';
        }else if(lstInv.size() == 0){
            String token;
            if(!Test.isRunningTest()){
                token = UnicommerceAuthentication.getAuthenticationToken();  
            }
            String res = GetSalesOrder.getSalesOrder(saleOrderCode, token);
            System.debug('status '+res);
            if(res == 'Error'){
                status = 'Error';
            }else if(res == 'Success'){
                
                Id OppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Cancelled Order').getRecordTypeId();            
                List<Opportunity> lstOpp= [Select id,StageName,RecordTypeId from Opportunity where Id=:recordId limit 1];
                Approval.UnlockResult[] urList = Approval.unlock(lstOpp, false);
				for(Approval.UnlockResult ur : urList) {
                    if (ur.isSuccess()) {
                        // Operation was successful, so get the ID of the record that was processed
                       // System.debug('Successfully unlocked opp with ID: ' + ur.getId());
                        if (lstOpp != NULL)
                        {
                            lstOpp[0].StageName = 'Cancelled';
                            lstOpp[0].RecordTypeId =OppRecordTypeId;
                            update lstOpp[0];
                        }
                        status = 'Success';
                        UnicommerceSalesOrderUtility.cancelSalesOrder(saleOrderCode, 'Cancelled');
                        Approval.lock(lstOpp,false);
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : ur.getErrors()) {
                            System.debug('The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Opp fields that affected this error: ' + err.getFields());
                        }
                    }
                } 
               
            }
        }        
        return status;
    }
}